### ISSUE TITLE
Sending Emails

### ISSUE THREAD

**Issue by AnubhavUjjawal** [Gradient-IIITS/IIIT-Council-Backend#2]
- [ ] Configure Django to send email using mailgun.

NOTE: Keep API keys in env variables and load them appropriately.

**Comment by masterashu** [comment]
Do we need to keep track of sent emails or failed emails?

**Comment by masterashu** [comment]
Sir, will we use SMTP or API?

**Comment by AnubhavUjjawal** [comment]
> Do we need to keep track of sent emails or failed emails?

No, not for now.

**Comment by AnubhavUjjawal** [comment]
> Sir, will we use SMTP or API?

SMTP
