### ISSUE TITLE
Configure Logging

### ISSUE THREAD

**Issue by AnubhavUjjawal** [Gradient-IIITS/IIIT-Council-Backend#7]
Configure Logging in Django. Refer to [this](https://docs.djangoproject.com/en/2.2/topics/logging/). Use `RotatingFileHandler`

**Comment by masterashu** [comment]
Sir, would we use sentry for Logging,  or just write logs in files.

**Comment by masterashu** [comment]
Should the log file details need to mentioned in environment variables or it is fine to mention it in settings.py ?

**Comment by AnubhavUjjawal** [comment]
Details needn't be in env variables.
We e don't need to use sentry for now.
